version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ./:/workspace:delegated
      # - node_modules:/usr/src/app/node_modules
    tty: true
# volumes:
#   node_modules:
